### ISSUE TITLE
Commands and --instance option

### ISSUE THREAD

**Issue by mlocati** [concretecms/console#31]
At the moment, every command accepts the `--instance` option.

BTW not all commands may implement the `InstallationAwareInterface` interface,

For example, here's the output of `concrete help self-update`:

```
Usage:
  self-update

Options:
  -h, --help               Display this help message
  -q, --quiet              Do not output any message
  -V, --version            Display this application version
      --ansi               Force ANSI output
      --no-ansi            Disable ANSI output
  -n, --no-interaction     Do not ask any interactive question
  -I, --instance=INSTANCE  Specify the concrete5 directory [default: "."]
  -v|vv|vvv, --verbose     Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Help:
  Update concrete.phar to the latest version.
```

IMHO we should add the `--instance` option only to commands implementing `InstallationAwareInterface` (not sure about how this can be done though).

**Comment by KorvinSzanto** [comment]
Realistically I don't think we're going to have more than a single command that ignores this value. Does it really make sense to add extra code to every other command to avoid having a no-op option in that one command? I'm not so sure yet.

**Comment by mlocati** [comment]
I'm thinking about a coding style checker/fixer that can use a concrete installation, but also may be disjointed from it (think for example at fixing the coding style of the code of a package)

**Comment by KorvinSzanto** [comment]
That makes sense, though for that command you'd likely want a way to specify the package directory through an option the same way you can specify an instance, so I wonder if it makes sense to replace this `--instance` option with something more generic like `--cwd` or something so that it can handle both of those cases.

**Comment by mlocati** [comment]
Yep, or `--path`, which is a little less technical

**Comment by KorvinSzanto** [comment]
How about #38 to avoid `--instance` on `self-update` and we add a new issue to replace `--instance` with `--path`. That way we'll capture both changes in the changelog
